### ISSUE TITLE
Add stats functions

### ISSUE THREAD

**Issue by pmos69** [vast-io/vast#104]
**Feature request:**
Besides resultsets with records,query responses might, alternatively, produce statistical results over the query results.

**Motivation:**
From an analyst perspective, some statistical queries are usually part of the workflow.
They allow the steering of big data queries without having to output very large resultsets.

Example of possible query syntax for statistics (for illustration purposes only):
`<query> [ | StatsFunction1 StatsFunction2 ...]`
The resultset for this query would be something like:
`{"StatsFunction1" : value, "StatsFunction2" : value, ...}`

As a first approach, some stats functions that could easily be split into multiple work units could be implemented, like (for illustration purposes only):
- `count()`         : return a count of all records in the query results
- `count(FIELD)`        : return a count of records in the query results that have the specified field
- `dc(FIELD)`       : return a count of unique values of FIELD in the query results
- `values(FIELD)`   : return a list of distinct values of FIELD in the query results
- `valuesC(FIELD)`  : return a list with the count of each distinct value of FIELD
- `max(FIELD)`      : return the highest value of FIELD in the query results
- `min(FIELD)`      : return the lowest value of FIELD in the query results
- `sum(FIELD)`      : return a sum of the values of FIELD in the query results
- `first(FIELD)`        : return the first seen (chronological) value of FIELD
- `last(FIELD*)`
  ...

Simplest way to start would be with a count() function, because it's the simplest one and would allow testing of the underlining framework. After that, field related functions.

Other simple improvments over the basic functionality include things like renaming of stats result fields (ex: `<query> [ | StatsFunction1 as name1 StatsFunction2 as name2 ...]`)
More advanced stats usualy include a grouping clause, outputing statistical  results grouped per distinct value of a specified field or field list, (ex: `<query> [ | StatsFunction1 StatsFunction2 ...] [ by FIELD]`
The complexity level of such an implementation can further  increase with features like evaluation of aritmetic operations and conditions over the stats functions, but the bigest usability gains come imediatelly from the implementation of basic stats.

**Comment by mavam** [comment]
Overall, I agree with you that many of these functions naturally occur in common analyses.

Up to this point, VAST doesn't do any computation that requires blocking. The lack of buffering rules out functions, such as `sort`, `unique`, `group-by`, or `top-k`. Of course, the current set of simple selection primitives is not sufficient and more will come in the future. The roadmap for adding new functionality for query features looks roughly like this:

1. Counting operations. This operation will be the first one, as bitmap indexes support it naturally.
2. Probabilistic summary statistics. Each queryable field can be equipped with probabilistic data structures (e.g., Bloom filters, HLL, CMS, etc.) to support queries like `cardinality` or `top-k`.
3. Interface with Spark. For arbitrarily complex queries over large result sets, VAST will only compute the index hits itself and load the raw events from the archive into Spark for further computation directly.

**Comment by pmos69** [comment]
Nice.
Counting operations are of immense value when analyzing data and trying to drill-down on issues.

Splunk has very nice support for complex queries, all sorts of statistical functions and data manipulation capabilities (a thing of beauty, really), but any processing that can be done in Vast itself and avoid transferring large resultsets for as many operations as possible would be beneficial. (As long as they fit in the Vast model).

**Comment by mavam** [comment]
We'll reconsider this issue after the first release. Closing it for now.
