### ISSUE TITLE
Vast killed for consuming all swap space

### ISSUE THREAD

**Issue by pmos69** [vast-io/vast#112]
Looks like a memory leak or unflushed data.

Successive imports make Vast RES usage continuously increase, until the processes is killed (FreeBSD) for using all available swap space.
from /var/log/messages:

```
...
Nov 18 09:56:53 bro kernel: swap_pager: out of swap space
Nov 18 09:56:53 bro kernel: swap_pager_getswapspace(16): failed
Nov 18 09:56:53 bro kernel: pid 48226 (vast), uid 1001, was killed: out of swap space
```

Here's a small script that makes Vast RES usage increase by about 2MB/s.
Swapper.py:

```
#!/usr/bin/env python

import subprocess,sys
import StringIO

text = '''#separator \\x09
#set_separator\t,
#empty_field\t(empty)
#unset_field\t-
#path\tSwapper
#open\t2015-10-08-14-55-06
#fields\tf1\tf2\tf3
#types\tstring\tstring\tstring
v1\tv2\tv3
#close\t2015-10-08-14-55-06
'''

text=text*1000

full_cmd = ['/usr/local/bin/vast', 'import', 'bro']

output = StringIO.StringIO()
output.write(text)

try:
  while 1:
    p = subprocess.Popen(full_cmd, stdin=subprocess.PIPE, stdout=subprocess.PIPE,
                     stderr=sys.stderr)
    out, out_err = p.communicate(input=output.getvalue())
except KeyboardInterrupt:
  pass
```

**Comment by pmos69** [comment]
Stopping all imports does not make Vast start any other activity.
Using ```vast send index flush``` flushes all indexes to disk but does not free any memory.
Using ```vast stop``` makes Vast terminate thousands of :: event-data-indexer actors.

**Comment by mavam** [comment]
I'll close this one for now since it's relating to a code base that has since been revamped. If the issue still persists, we can consider reopening it.
