### ISSUE TITLE
libvast/vast/expected.hpp:10:27: error: ‘no_error’ is not a member of ‘caf’  constexpr auto no_error = caf::no_error;

### ISSUE THREAD

**Issue by MarcinNaw** [vast-io/vast#117]
Make for VAST fails for most recent Version of CAF+VAST.

libvast/vast/expected.hpp:10:27: error: ‘no_error’ is not a member of ‘caf’
 constexpr auto no_error = caf::no_error;

**Comment by josephnoir** [comment]
Hi Marcin,

I think `no_error` was only recently added and is not yet merged into the master.
VAST depends on the develop branch of CAF. Which branch are you using? 

Raphael

**Comment by MarcinNaw** [comment]
I just did ` git clone https://github.com/vast-io/vast.git `, is this the wrong branch?

**Comment by josephnoir** [comment]
For VAST that is fine, but for CAF you should `git checkout develop`.

**Comment by MarcinNaw** [comment]
I just did `git clone https://github.com/actor-framework/actor-framework.git`. Yep, that's the wrong branch. `git checkout develop` helped. @josephnoir thank you for the fast support!

**Comment by josephnoir** [comment]
You're welcome!
