### ISSUE TITLE
Combing the same expression with && or || does not return a result

### ISSUE THREAD

**Issue by josephnoir** [vast-io/vast#126]
Using the same log the query `vast export ascii -h "proto == \"tcp\" || proto == \"tcp\""` does not return a result while `vast export ascii -h "proto == \"tcp\""` returns the expected rows. This was reproducible with different queries in our local setup.

**Comment by mavam** [comment]
Per @josephnoir, the following query does not terminate:

    (id.resp_p == 137/? || id.resp_p == 138/? || id.resp_p == 445/?) && proto == "tcp"

This may be related, we have to investigate.

**Comment by josephnoir** [comment]
This query `(id.resp_p == 137/? || id.resp_p == 138/? || id.resp_p == 445/?) && proto == "tcp"` does not terminate, but returns results.

In contrast, this one `(id.resp_p == 138/? || id.resp_p == 138/? || id.resp_p == 445/?) && proto == "tcp"` will neither terminate nor return results.

The ports of the first two expression are the same in the second query. That is how I noticed this. Might still be related, don't know how this is processed in VAST.
