### ISSUE TITLE
Provide a safe way to persist state

### ISSUE THREAD

**Issue by josephnoir** [vast-io/vast#128]
Since the query language is a bit unstable at the moment, having a safe way to persist state sounds very useful, as crashing the VAST instance often corrupts state. Moreover, a safe way to shutdown a VAST instance sounds like a good idea in general!

From the Gitter channel:
> I encounterd this as well, it is definitely on my to do list. Where I want to arrive: CTRL+C once shuts an instance down safely, the second CTRL+C creates a hard abort with potential state loss.

**Comment by mavam** [comment]
We're tracking this issue internally, closing it for now.
