### ISSUE TITLE
Fix continuous queries

### ISSUE THREAD

**Issue by josephnoir** [vast-io/vast#131]
Passing the `-c` or `-u` options to `vast export` leads to the same behavior as using `-h`. The expected behavior would be to keep the export process alive and get new results when matching data is imported.

From the Gitter conversation:
> Architecturally, there are two designs possible: (1) the traditional streaming system: events go directly from the importer through all exporters (2) index-based triggers: continuous queries are applied after successful indexing to the new index.
> Option (1) makes more sense from a complexity and latency perspective, while option (2) reuses the existing query architecture, ensuring you'll always get the same results for historical and continuous queries.

**Comment by mavam** [comment]
Closing this one, as #142 is our new vehicle to discuss this concern.
