### ISSUE TITLE
Add filter expressions to import functionality

### ISSUE THREAD

**Issue by MarcinNaw** [vast-io/vast#134]
[Feature Request]

The export command allows filtering of data with expressions such as: 
`vast export pcap "port > 60000/tcp"`

Let's say I have a very large data set and I am only interested in analyzing a specific subset, it would be beneficial to allow filtering data while importing.

Currently, the workflow would be:

1. import all data in vast DB
2. export data using filter expression
3. import filtered data and save it in a new vast db
4. analyse

I would like to combine steps (1-3):

1. import data using filter expression in vast DB
2. analyse

Possible syntax: 
`    vast import pcap "sport > 60000/tcp" < trace.pcap`

**Comment by mavam** [comment]
That's definitely an important feature. Using the query language as import filter language is also a natural fit.

We could also allow more fine-grained filtering through specification of *custom schemas* during the import. I'll shorty write a section in the man page about that and will get back here.

**Comment by josephnoir** [comment]
From our mail exchange I am not sure that we all agree on what this should do.

- My first thought when reading this issue was that the filter only imports matching events and drops the rest. Short: a filter for what is imported.
- The other impression I got was that query filters the imported data for events that are exported directly while all events from the file are imported into the database.

Would be nice if we could clarify this!

**Comment by MarcinNaw** [comment]
> My first thought when reading this issue was that the filter only imports matching events and drops the rest. Short: a filter for what is imported.

+1, this is exactly what I meant.

**Comment by mavam** [comment]
I think we're in sync here: the first bullet captures the semantics from a user perspective. There are two ways to implement this internally:

1. Filter directly at the source as the events are parsed
2. Filter at the importer when the events enter the system

Approach (1) puts the filtering burden on the data sources and trades better I/O efficiency for some extra CPU cycles at the endpoints. Approach (2) puts more pressure on the importer and simplifies the sources. It is also symmetric in the architecture: exporter filter queries, importers filter ingested data.

In general, filtering earlier is a sensible design choice. It may limit us in the future when it comes to correlation and telemetry about dropped events. (For example, we may want to store summary statistics of their data.)
