### ISSUE TITLE
Queries for ":subnet in prefix" not terminating

### ISSUE THREAD

**Issue by MarcinNaw** [vast-io/vast#135]
[Bug report]

Consider the following queries:

1. `vast export ascii ":subnet == 103.16.124.0/22"`
2. `vast export ascii ":subnet in 103.16.124.0/22"`

Query 1) works as expected, however query 2) retrieves no data and does not terminate. The VAST backend accepts the query, but does not find any matching indexes.

**Use case for query 2):** 

Lets say my prefix is 103.16.124.0/22 and I have imported a bunch of BGP data (RIPE RIS, Routeviews etc). I want to check for hijacks by searching for announcements that involve more specific prefixes, hence prefixes that are "in" the prefix.

**Comment by mavam** [comment]
Looks like there are two issues here:

- [ ] "subnet in subnet" queries are [not (yet) supported](https://github.com/vast-io/vast/blob/b48eb9eed53bc5f112a93bcae63135cff49a89fd/libvast/src/value_index.cpp#L361):
       expected<bitmap>
       subnet_index::lookup_impl(relational_operator op, data const& x) const {
         if (!(op == equal || op == not_equal))
           return make_error(ec::unsupported_operator, op);

- [ ] The (currently malformed) query does not terminate.

**Comment by mavam** [comment]
I've addressed (1) via 33d84ff. There now exist two semantics for "subnet in subnet" lookups. Let *U* be the subnet index and *x* be the element to lookup in the index. The following expressions are valid:

1. `U ni x` signifies *U ⊆ x*, i.e., the lookup returns all subnets in *U* that are a subset of *x*.
2. `U in x` signifies *U ⊇ x*, i.e., the lookup returns all subnets in *U* that contain *x*.

Think of operator `ni` as essentially `in` but just "in the other direction" since it's not symmetric.

Please let me know if your were expecting different semantics.

**Comment by josephnoir** [comment]
The query is now accepted by VAST, but the `exporter ignores false positive[s]` that should not actually false. For example, for the query `:subnet in 218.88.0.0/14`, the importer ignores the following entry.
```
bro::bgpupdates [1000661|+1499937568000000000ns] ["route-views.saopaulo", +1499937568000000000ns, "A", 23650, 218.90.232.0/24]
```
The last value is the subnet `218.90.232.0/24`. Since this is less specific, I'd expect the query to return the result and not discard it.
```
218.88.../14: 1101 1010 0101 1000
218.90.../24: 1101 1010 0101 1010
                              ^
```

**Comment by MarcinNaw** [comment]
Just to have a common data set for debugging:
```
#separator \x09
#set_separator	,
#empty_field	(empty)
#unset_field	-
#path	bgpupdates
#open	2017-07-15-12-20-50
#fields	collector	ts	type	origin	prefix
#types	string	time	string	count	subnet
route-views2	1499894474.0	A	4134	218.88.0.0/14
route-views.eqix	1499896979.0	A	4134	218.89.0.0/16
route-views.linx	1499911521.0	A	38283	218.89.167.0/24
```

Expected output:
`vast export ascii "prefix in 218.89.0.0/16"`

--> rows for 218.89.0.0/16 and 218.89.167.0/24

`vast export ascii "prefix ni 218.89.0.0/16"`

--> rows for 218.88.0.0/14 and 218.89.0.0/16

**Comment by josephnoir** [comment]
On a related note, now I get an error for `vast export ascii ":addr in 10.0.0.0/8"`--the example from the [man page](https://github.com/vast-io/vast/blob/master/doc/vast.1.md)--which returns:
```
failed to spawn exporter: got syntax_error: ("type extractor type check failure", addr, in, 218.90.232.0/24)
```

**Comment by MarcinNaw** [comment]
I can confirm, queries with column name vs. column type produce different results.

`vast export ascii "prefix in 218.89.0.0/16"`

Query does not terminate, no output, backend reports that the event-indexer failed to resolve predicate: got type_clash: (subnet, in, 218.89.0.0/16).


`vast export ascii ":subnet in 218.89.0.0/16"`

Query terminates with no output, backend informs about the exporter ignoring false positive, which are actually the correct result.

**Comment by mavam** [comment]
@MarcinNaw: Just a quick note: now that "subnet in subnet" queries are allowed, it looks like we need to adjust the type system. Does this patch fix the issue?

```diff
--- a/libvast/src/type.cpp
+++ b/libvast/src/type.cpp
@@ -627,7 +627,7 @@ bool compatible(type const& lhs, relational_operator op, type const& rhs) {
     case not_in:
       if (is<string_type>(lhs))
         return is<string_type>(rhs) || is_container(rhs);
-      else if (is<address_type>(lhs))
+      else if (is<address_type>(lhs) || is<subnet_type>(lhs))
         return is<subnet_type>(rhs) || is_container(rhs);
       else
         return is_container(rhs);
```

I'll look into the termination and false positive issue tomorrow.

**Comment by MarcinNaw** [comment]
@mavam Unfortunately, this Diff has no effect for me. :(

I still got the type_clash and no termination for `vast export ascii "prefix in 218.89.0.0/16"`.

**Comment by mavam** [comment]
Ok, I'll investigate...

**Comment by MarcinNaw** [comment]
Can confirm, works as expected. Good job.
