### ISSUE TITLE
Refactor flow control implementation

### ISSUE THREAD

**Issue by mavam** [vast-io/vast#70]
Per the discussion in [8f57f6](https://github.com/mavam/vast/commit/8f57f6c4f711f947061810f6d537f13b667ed284#commitcomment-11174442), the flow control implementation should be reimplemented as a separate actor to facilitate actor composition.

**Comment by Neverlord** [comment]
:+1:

**Comment by mavam** [comment]
Explicit flow control is no longer on the menu. Instead, we'll switching to CAF streams for subsets of the implementation.
