### ISSUE TITLE
Consolidate program option handling and command line parsing

### ISSUE THREAD

**Issue by mavam** [vast-io/vast#89]
VAST currently relies exclusively on CAF's simple `extract_opts` functionality for command line parsing and option handling. We need a more powerful abstraction for handling program configuration that can be used across client and server side, that provides uniform access to help texts, and ideally also offers a simple configuration file (INI or YAML) to load/store a VAST node configured at runtime.

**Comment by Neverlord** [comment]
Is this related to the "treat arguments as command" we discussed for CASH recently?

**Comment by mavam** [comment]
Yes, this is closely related, and ideally CASH would address this issue entirely. Some examples, what bothers me at the moment.

1. I want a unified error interface when I send a message `<"vast", "spawn", "--invalid-option">` and the `spawn` command does not support. If the command is malformed, I want a syntax error as response. If it fails, and error, and if it succeeds, I want an OK atom or whatever message the command returns.

2. I want the ability to generate a global help text. Right now, even I have to look in the source code to figure out what options each command supports. I also want that in a network-transparent way, so that any actor can inquire how to use a specific command.

3. I want a declarative way to describe my per-node topology. For example, to run a cluster, right now I have to do this:

        vast spawn archive <args>
        vast spawn index <args>
        vast spawn importer <args>
        vast connect importer archive
        vast connect importer archive
        ...

    Each of this "topology-mutating" commands should be tracked, so that I can simply restart the node when it crashes and it re-applies the command sequence automatically. This requires a notion of configuration persistence. I could see a simple YAML config achieving that.
